require: rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'gemfiles/**/*'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

MultilineMethodCallIndentation:
  EnforcedStyle: indented

MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
