language: ruby
# Ruby versions to run tests on.
# We will not test on Ruby versions thar are no longer supported (EOL).
# List of Ruby releases: https://www.ruby-lang.org/en/downloads/releases/
# Maintenance status of each Ruby series https://www.ruby-lang.org/en/downloads/branches/
rvm:
  - 2.4.4
  - 2.5.3
  - 2.6.1
  - ruby-head
# Rails versions to run tests on.
# We will not test on Rails versions thar are no longer supported (EOL).
# List of Rails releases: https://rubygems.org/gems/rails/versions
# Maintenance status of each Rails series: https://guides.rubyonrails.org/maintenance_policy.html
env:
  - RAILS_VERSION=4.2.11
  - RAILS_VERSION=5.2.2
  - RAILS_VERSION=6.0.0.beta2
  - RAILS_VERSION=master
matrix:
  # When testing against the head or master (unreleased versions) of Ruby or
  # Rails, failures may occur because the branch is unstable and not due to our
  # project. For these cases, we'll allow failures until official versions are
  # released.
  allow_failures:
    - env: RAILS_VERSION=master
    - rvm: ruby-head
  # Some Rails versions do not work with older Ruby versions.
  exclude:
    # Rails >= 6 requires Ruby version >= 2.5.0
    - rvm: 2.4.4
      env: RAILS_VERSION=6.0.0.beta2
    - rvm: 2.4.4
      env: RAILS_VERSION=master
    # I was unable to get Ruby head to work with Bundler < 2, which is required by Rails 4.2.
    - rvm: ruby-head
      env: RAILS_VERSION=4.2.11
# See https://docs.travis-ci.com/user/caching/#bundler
cache: bundler
sudo: false
before_install:
  # Rails ~> 4.2.x does not work with Bundle 2.0. The gem uninstall command
  # removes any Bundler 2.x installed in RVM’s “global” gemset during the Ruby run
  # time installation, which would be selected as the default bundle command. We
  # ignore the failure from that command, because the failure most likely means
  # that there was no matching Bundler version to uninstall.
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2' --no-document
script:
  - bundle exec rubocop
  - bundle exec rspec
notifications:
  email: false
